
version: '3'
services:
  couchserver:
    image: couchdb
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
        - ./dbdata:/opt/couchdb/data

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - api
      - client

  api:
    build:
      dockerfile: Dockerfile
      context: "./api"
    ports:
      - "3001:3001"
    volumes:
      - /app/node_modules
      - ./api:/app
    depends_on:
    - couchserver 
   

  www:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./www
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./www:/app
    environment:
      - CHOKIDAR_USEPOLLING=true


