
version: '3'
services:
  couchserver:
    image: couchdb
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
      # - COUCHDB_NODENAME=couchdb@127.0.0.1
    volumes:
        - ./dbdata:/opt/couchdb/data

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "8080:8080"

  api:
    build:
      dockerfile: Dockerfile
      context: "./api"
  
    depends_on:
    - couchserver
   
      
    ports:
      - "3001:3001"
    volumes:
      - /app/node_modules
      - ./api:/app

  www:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./www
    volumes:
      - /app/node_modules
      - ./www:/app
    ports:
      - "3000:3000"

