# version: '3.8'

# services:

#   mongo:
#     image: 'mongo:4.4'
#     restart: always
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: example

#   mongo-express:
#     image: mongo-express
#     restart: always
#     ports:
#       - 8081:8081
#     environment:
#       ME_CONFIG_MONGODB_ADMINUSERNAME: root
#       ME_CONFIG_MONGODB_ADMINPASSWORD: example
#       ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
version: '3'
services:
  couchserver:
    image: couchdb
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
        - ./dbdata:/opt/couchdb/data

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "8080:8080"

  api:
    build:
      dockerfile: Dockerfile
      context: "./api"
    # depends_on:
    #   - mongo
    depends_on:
      - couchserver
    ports:
      - "3001:3001"
    volumes:
      - /app/node_modules
      - ./api:/app

  www:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./www
    volumes:
      - /app/node_modules
      - ./www:/app
    ports:
      - "3000:3000"

  # adminer:
  #     image: adminer:latest
  #     restart: unless-stopped
  #     ports:
  #       - 8000:8080
  #     depends_on:
  #       - mysql_db
  #     environment:
  #       ADMINER_DEFAULT_SERVER: mysql_db
